 version: "3" 

 services:
   orion:
     image: fiware/orion
     ports:
       - "1026:1026"
     command: -dbhost "ola-mongo-east-2.mongo.cosmos.azure.com:10255" -db "fiver_db" -dbuser "ola-mongo-east-2" -dbpwd "4sJXSYukOF1O4QkhnUycOxyxjZ4a6MtVPL6U7xmpsryqtocXPqAsMPckszwRHWEf9YWVzps7iV71yds45wTyGg==" -dbSSL -dbDisableRetryWrites -logLevel DEBUG -t 100